# ( Line ) Topology: Camera -> Encoder -> Transcoder -> Decoder -> Rendering -> User ( Receiver )

# Camera <-> SFF1 ( Network: 10.0.1.0/24 )
camera[0]="camera_sff1"
sff1[0]="camera_sff1"

# SFF1 <-> Encoder ( Network: 10.0.2.0/24 )
sff1[1]="sff1_encoder"
encoder[0]="sff1_encoder"

# SFF1 <-> SFF2
sff1[2]="sff1_sff2"
sff2[0]="sff1_sff2"

# SFF2 <-> Transcoder ( Network: 10.0.3.0/24 )
sff2[1]="sff2_transcoder"
transcoder[0]="sff2_transcoder"

# SFF2 <-> Decoder ( Network: 10.0.5.0/24 )
sff2[2]="sff2_decoder"
decoder[0]="sff2_decoder"

# Decoder <-> Rendering ( Network:  )
decoder[1]="decoder_rendering"
rendering[0]="decoder_rendering"

# Decoder <-> Rendering ( Network:  )
rendering[1]="rendering_user"
user[0]="rendering_user"

# Docker Images
camera[image]="kathara/base"
sff1[image]="kathara/p4"
encoder[image]="coder"
sff2[image]="kathara/p4"
transcoder[image]="kathara/base"
decoder[image]="coder"

rendering[image]="kathara/base"
user[image]="kathara/base"